spring:
  datasource:
    url: jdbc:h2:mem:loans
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate.ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  config:
    import:
      - "application-qa.yaml"
      - "application-prod.yaml"
  profiles:
    active:
      - "qa"

build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934
